"""
VORTEX Contract Deployment Script
==================================
Deploy escrow contract to Algorand localnet.
Create and fund 3 oracle accounts.
Auto-write credentials to backend/.env.
"""

import os
import sys
from pathlib import Path

from algosdk import account, mnemonic
from algosdk.v2client import algod
from algosdk.transaction import PaymentTxn, wait_for_confirmation
from dotenv import set_key


def get_algod():
    url = os.getenv("ALGORAND_ALGOD_URL", "http://127.0.0.1:4001")
    token = os.getenv("ALGORAND_ALGOD_TOKEN", "a" * 64)
    return algod.AlgodClient(token, url)


def create_and_fund_account(client, funder_pk, name, amount_algo=10):
    """Create a new account and fund it from the funder."""
    pk = account.generate_account()[0]
    addr = account.address_from_private_key(pk)
    mn = mnemonic.from_private_key(pk)

    # Fund the new account
    funder_addr = account.address_from_private_key(funder_pk)
    sp = client.suggested_params()
    txn = PaymentTxn(funder_addr, sp, addr, int(amount_algo * 1_000_000))
    signed = txn.sign(funder_pk)
    tx_id = client.send_transaction(signed)
    wait_for_confirmation(client, tx_id, 4)

    print(f"  {name}: {addr}")
    print(f"  Funded: {amount_algo} ALGO")
    return {"private_key": pk, "address": addr, "mnemonic": mn}


def main():
    print("=" * 50)
    print("VORTEX Contract Deployment")
    print("=" * 50)

    client = get_algod()

    # Verify connection
    try:
        status = client.status()
        print(f"\n✓ Connected to Algorand (round {status['last-round']})")
    except Exception as e:
        print(f"\n✗ Cannot connect to Algorand: {e}")
        print("  Run: algokit localnet start")
        sys.exit(1)

    # Get default localnet account (dispensser)
    # AlgoKit localnet has a default funded account
    print("\n── Creating Oracle Accounts ──")

    # For localnet, generate a funder account
    # In real deployment, this would be the deployer's funded account
    default_pk, default_addr = account.generate_account()
    default_mn = mnemonic.from_private_key(default_pk)

    # Use KMD to get localnet default account
    try:
        from algosdk.kmd import KMDClient
        kmd = KMDClient("a" * 64, "http://127.0.0.1:4002")
        wallets = kmd.list_wallets()
        default_wallet = next(w for w in wallets if w["name"] == "unencrypted-default-wallet")
        handle = kmd.init_wallet_handle(default_wallet["id"], "")
        keys = kmd.list_keys(handle)

        if keys:
            default_addr = keys[0]
            default_pk = kmd.export_key(handle, "", default_addr)
            print(f"  Using localnet default account: {default_addr[:8]}...")
        kmd.release_wallet_handle(handle)
    except Exception as e:
        print(f"  KMD not available: {e}")
        print("  Using generated accounts (fund manually)")

    # Create 3 oracle accounts
    oracle_1 = create_and_fund_account(client, default_pk, "Oracle 1", 10)
    oracle_2 = create_and_fund_account(client, default_pk, "Oracle 2", 10)
    oracle_3 = create_and_fund_account(client, default_pk, "Oracle 3", 10)

    # Create buyer account for testing
    buyer = create_and_fund_account(client, default_pk, "Test Buyer", 100)

    print("\n── Deploying Escrow Contract ──")
    print("  Note: Contract compilation requires Puya compiler")
    print("  Run: algokit compile contracts/escrow.py")
    print("  For hackathon: use pre-compiled TEAL or mock app_id")

    # For hackathon, create a placeholder app
    # In production, compile with Puya and deploy
    app_id = 1001  # Placeholder — replace with actual deployment

    print(f"\n  App ID: {app_id}")

    # Write to backend/.env
    env_path = Path(__file__).parent.parent / "backend" / ".env"
    print(f"\n── Writing to {env_path} ──")

    env_content = f"""# Auto-generated by deploy.py
ALGORAND_ALGOD_URL=http://127.0.0.1:4001
ALGORAND_ALGOD_TOKEN={"a" * 64}
ALGORAND_INDEXER_URL=http://127.0.0.1:8980
ORACLE_1_MNEMONIC="{oracle_1['mnemonic']}"
ORACLE_2_MNEMONIC="{oracle_2['mnemonic']}"
ORACLE_3_MNEMONIC="{oracle_3['mnemonic']}"
OPENAI_API_KEY={os.getenv('OPENAI_API_KEY', 'sk-...')}
SECRET_KEY=vortex-dev-secret-key-change-in-prod
DATABASE_URL=sqlite:///./vortex.db
DOCKER_HOST=unix:///var/run/docker.sock
ENVIRONMENT=development
CORS_ORIGIN=http://localhost:3000
APP_ID={app_id}
BUYER_MNEMONIC="{buyer['mnemonic']}"
"""
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(env_content)
    print("  ✓ .env written")

    print("\n" + "=" * 50)
    print("DEPLOYMENT COMPLETE")
    print("=" * 50)
    print(f"\n  App ID:     {app_id}")
    print(f"  Oracle 1:   {oracle_1['address'][:12]}...")
    print(f"  Oracle 2:   {oracle_2['address'][:12]}...")
    print(f"  Oracle 3:   {oracle_3['address'][:12]}...")
    print(f"  Buyer:      {buyer['address'][:12]}...")
    print(f"\n  Next: cd backend && uvicorn main:app --reload")


if __name__ == "__main__":
    main()
