"""Add tracking fields for production startup hardening

Revision ID: 496694dbe80b
Revises: 71bc42e9e97d
Create Date: 2026-04-15 21:39:26.666202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496694dbe80b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escrow_verified', sa.Boolean(), nullable=True))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_step', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('processing_started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('processing_started_at')
        batch_op.drop_column('last_error')
        batch_op.drop_column('verification_step')

    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.drop_column('escrow_verified')

    # ### end Alembic commands ###
