"""Initial schema batch support

Revision ID: 71bc42e9e97d
Revises: 
Create Date: 2026-04-15 21:29:19.245008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bc42e9e97d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arbiter_votes', schema=None) as batch_op:
        batch_op.alter_column('vote',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('resolution',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('oracle_votes', schema=None) as batch_op:
        batch_op.alter_column('vote',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)

    with op.batch_alter_table('oracle_votes', schema=None) as batch_op:
        batch_op.alter_column('vote',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.alter_column('resolution',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('asset_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('arbiter_votes', schema=None) as batch_op:
        batch_op.alter_column('vote',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
